.gitignore, python/dataverse_sdk/__init__.py, python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/connections.py, python/dataverse_sdk/constants.py, python/dataverse_sdk/schemas/api.py, python/dataverse_sdk/schemas/client.py, python/dataverse_sdk/schemas/common.py, python/requirements/requirements.txt
Refactor the SDK.
- Add connections object to better handle the dataverse client connections.
- Get client manually in `Dataverse.create_XYZ` static methods.
- Remove `config` from `requirements.txt`.
- Add lost fields e.g. `render_pcd`.
- It should pass the debug script pasted in BE chat.
=> feat(python): refactor

python/README.md, python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/schemas/client.py, python/setup.py
- As title.
- [AB#13869](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/13869)
- Add `MLModel` basemodel in schema
- Add `list model` function in DataverseClient and Project class
- Add `get_model` function for getting model detail information in DataverseClient and Project class
- Add `get_label_file` and `get_triton_model_file` for getting model related files. (WILL TEST after API update )
The `list_models` method will list all the models in the given project
```Python
#1
models = client.list_models(project_id = 1)
#2
project = client.get_project(project_id=1)
models = project.list_models()
```
The `get_model` method will get the model detail info by the given model-id
```Python
model = client.get_model(model_id=30)
model = …
```
=> feat(python): add feature to list model and get model detail

python/README.md, python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/schemas/client.py, python/setup.py
As title
- [AB#16730](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/16730)
- Add `model_format` argument for `get_ml_model_file` for getting different model files with backend api
- Add `get_onnx_model_file` function for user to download onnx file
- Adjust `list_ml_models` function for getting model list with the type="projects"
- list model could work normally
- onnx file can be downloaded.
=> feat(python): be able to downlaod onnx model and adjust list_model

python/dataverse_sdk/apis/backend.py
as mentioned
- modify `access_key_id` field and `secret_access_key` logic validation, we need to make sure all keys are assigned or are keys are not assigned
it should work.
=> fix(python): update access key validation logic

python/README.md, python/dataverse_sdk/constants.py, python/setup.py
as mentioned.
- [AB#17589](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/17589)
- Modify domain name in `DataverseHost`
- update README
=> feat(python): modify domain

python/README.md, python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/constants.py, python/dataverse_sdk/exceptions/client.py, python/dataverse_sdk/schemas/common.py, python/setup.py
same as title
- [AB#20112](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/20112)
- [AB#20114](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/20114)
- [AB#20137](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/20137)
- support upload visionai format, image format directly from local
- implement async upload 
- upload from local
```python3
from dataverse_sdk import DataverseClient, DataverseHost
from dataverse_sdk.schemas.client import Project
from dataverse_sdk.schemas.common import AnnotationFormat, DatasetType, DataSource
client = DataverseClient(
host=DataverseHost.LOCAL,
email="bc51f3c57a5e9cdbb8a74614@local.email.com",
password="Pass1234", …
```
=> feat(curation): add service_id

python/README.md, python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/constants.py, python/setup.py
add access_token for auth
- [AB#20112](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/20112)
- add `access_token` which can instead of password. but no refresh mechanism for it
- add `get_user` method, that observ need to check the `role`
- update readme
- fix host url, need to change it when we update demo & production site
=> feat: add access_token to do auth

python/dataverse_sdk/apis/backend.py, python/setup.py
...
- [AB#21198](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/21198)
- The type of model is changed from "project" to "trained"
- list trained model by SDK
- We could list the models trained on Dataverse and download the model related files
=> fix(python): list model api with trained models

python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/exceptions/client.py, python/setup.py
...
- [AB#21394](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/21394)
- Add `DataverseExceptionBase` , `AsyncThirdPartyAPIException`  schema
- Raise the exception as api response
- The error code could be forwarded
- The DataVerse error code will be modified as the table
=> feat(python): add api error exception schema and remaining the status code

python/README.md, python/dataverse_sdk/client.py, python/dataverse_sdk/connections.py, python/dataverse_sdk/constants.py, python/dataverse_sdk/schemas/common.py, python/tools/import_dataset_from_local.py
...
- [AB#21439](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/21439)
- [AB#21610](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/21610)
- Modify the data source naming (from SDK to LOCAL) for `importing local data by SDK`
- Add example script for import dataset from local
- Modify site URL
-- The script could run successfully
```
python tools/import_dataset_from_local.py -host https://dev.visionai.linkervision.ai/dataverse/curation -e {your-account-email} -p {PASSWORD} -s {service-id}  -project {project-id} --folder {/YOUR/TARGET/LOCAL/FOLDER} -name {dataset-name} -type {raw_data OR annotated_data} -anno {image OR vision_ai} --sequential
```
-- Could connect to DEV site with new URL
=> feat(python): change host url and adjustment for local dataset upload

python/dataverse_sdk/client.py, python/dataverse_sdk/schemas/client.py, python/setup.py
...
- [AB#23891](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/23891)
- [AB#24143](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/24143)
- Allow empty string update
- Add status filed in ConvertRecord
- ...
- Should update curation BE for allowing empty string as well
=> fix(python): allow empty string update and add status in ConvertRecord

python/README.md, python/dataverse_sdk/client.py, python/dataverse_sdk/exceptions/client.py, python/dataverse_sdk/schemas/client.py, python/dataverse_sdk/schemas/common.py, python/dataverse_sdk/utils/utils.py, python/setup.py, python/tools/import_dataset_from_local.py
...
- [AB#23709](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/23709)
- Add yolo format for create dataset and validating local data structure for local import
- Adjust alias with only updating empty alias if the alias is created before
- yolo format dataset could be imported from local
- could update empty alias by SDK
=> feat(python): import yolo with validating local import folder structure  and adjustment for alias updating

python/README.md, python/dataverse_sdk/__init__.py, python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/exceptions/client.py, python/dataverse_sdk/schemas/api.py, python/dataverse_sdk/schemas/client.py, python/dataverse_sdk/schemas/common.py, python/setup.py
...
- [AB#24724](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/24724)
- [AB#24986](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/24986)
- Add VQA image type and adjust the validation for rank
- Be able to create VQA project
- Be able to edit VQA ontology
- Be able to download the VQA question list.
- Be able to improt VLM dataset (To be testing)
The `create_vqa_project` method will create project on the connected site with the defined questions/answer_type.
* Example Usage:
```Python
question_answer = [ QuestionClass(class_name="question1", rank=1, question="Is any person found in the picture?",     
answer_type="boolean"),
QuestionClass(class_name="question2", rank=2, question="What is the blob color …
```
=> feat(python): be able to create VQA project, edit the VQA ontology, import dataset as vlm format

python/dataverse_sdk/client.py, python/setup.py
- [AB#25360](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/25360)
- Previously, the rank is not considered for adding ontology classes
- Create ontology classes with rank and do validation
- It could work
=> fix(python): add new onyology classes with rank and do validation

python/README.md, python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/schemas/client.py, python/setup.py
...
- [AB#26311](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/26311)
- Add function to call api to download onnx model
- User could get onnx model file with convert_record_id
=> feat(python): able to download onnx file for the conveted model

python/README.md, python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/schemas/client.py, python/dataverse_sdk/utils/utils.py, python/setup.py, python/tools/export_dataslice.py, python/tools/import_vqa_dataset.py
...
- [AB#26766](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/26766)
- Add function for list dataaslices/ get dataslice data
- Add function for triggering export dataslice and download (only support get the "direct_download" zip file for now)
- Add script for import vqa dataset
- Add script for export dataslice
- Adjust local import parameters
Users could run the script below.
```
python tools/import_vqa_dataset.py -host https://staging.visionai.linkervision.ai/dataverse/curation -e {your-account-email} -p {PASSWORD} -s {service-id} -project {project-id} --folder {/YOUR/TARGET/LOCAL/FOLDER} -type {raw_data OR annotated_data}
```
```
python tools/export_dataslice.py -host https://staging.visionai.linkervision.ai/dataverse/curation  -e …
```
=> feat(python): add function for getting dataslice, triggering export dataslice, and download export data

.pre-commit-config.yaml, python/dataverse_sdk/client.py, python/setup.py
...
- [AB#26793](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/26793)
- ...
- change upload file to async version
- add progress bar for upload file
- update presigned url batch size
-  commitlint version update
- ...
=> feat(python): async image upload and add progress bar

python/dataverse_sdk/utils/utils.py, python/setup.py
...
- [AB#26986](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/26986)
- ...
-  change file type name check to case insensitive
- ...
=> feat(python): change file type name check to case insensitive

python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/setup.py, python/tools/import_dataset_from_local.py
...
- [AB#26567](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/26567)
- ...
- support custom import with local data source
- ...
=> feat(python): support custom import with local data source

python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/setup.py
...
- [AB#27032](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/27032)
- ...
- add async backend api 
- change generate presigned url to async version
- ...
=> feat(python): async backend api and presigned url generating

python/dataverse_sdk/client.py, python/dataverse_sdk/schemas/api.py, python/dataverse_sdk/schemas/client.py, python/setup.py
...
- [AB#27235](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/27235)
- 
- Upgrade to pydantic v2
- ...
=> feat(python): upgrade to pydantic v2

python/README.md, python/dataverse_sdk/export/coco.py, python/dataverse_sdk/export/constant.py, python/dataverse_sdk/export/exporter.py, python/dataverse_sdk/export/visionai.py, python/dataverse_sdk/export/vqa.py, python/dataverse_sdk/export/yolo.py, python/setup.py, python/tools/export_dataslice_large.py
...
- [AB#27526](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/27526)
- [AB#27558](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/27558)
- ...
- improve download performance
- download with original file name
- ...
=> feat(python): improve export performance and download with original file name

python/dataverse_sdk/client.py, python/dataverse_sdk/exceptions/client.py, python/setup.py
...
- [AB#27845](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/27845)
- ...
- enhance exception base object
- ...
=> fix(python): enhance exception base msg

python/dataverse_sdk/client.py, python/dataverse_sdk/export/visionai.py, python/setup.py
...
- [AB#27931](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/27931)
- 
- ...
- ...
=> fix(python): fix windows system file path

python/README.md, python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/export/coco.py, python/dataverse_sdk/export/visionai.py, python/dataverse_sdk/export/vqa.py, python/dataverse_sdk/export/yolo.py, python/dataverse_sdk/schemas/api.py, python/dataverse_sdk/schemas/client.py, python/setup.py, python/tools/import_dataset_from_local.py, python/tools/import_vqa_dataset.py
...
- [AB#28064](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/28064)
- [AB#28078](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/28078)
- ...
- remove sensor param from create dataset
- add export retry
- ...
=> fix(python): fix create dataset and add retry with exponential backoff

python/dataverse_sdk/export/constant.py, python/setup.py
...
- [AB#29368](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/29368)
- ...
- reduce export batch size
- ...
=> fix(python): adjust export batch size

python/README.md, python/dataverse_sdk/apis/backend.py, python/dataverse_sdk/client.py, python/dataverse_sdk/export/exporter.py, python/dataverse_sdk/schemas/client.py, python/dataverse_sdk/utils/utils.py, python/setup.py
...
- [AB#29669](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/29669)
- Update exporter for get datarows request
- Fix answer type validator as pydantic 2.0 upgrade
- Add list dataset function
- Export-large-dataslice and create-vqa-ontology could work successfully.
- list datasets could work
```Python
project = client.get_project(project_id=1)
datasets:list = project.list_datasets()
```
OR
```Python
datasets:list = client.list_datasets(project_id=1, client_alias=client.alias )
```
=> fix(python): fix answer type validator, add list dataset function, adjust get datarows for exporting

python/dataverse_sdk/client.py
...
- [AB#32886](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/32886)
- Return the question answer type/ option list when getting project question list
=> feat(python): add answer type/options in get question list
